// Code generated by internal/gen/services from services.json; DO NOT EDIT.
// SPDX-License-Identifier: MIT

package registry

import (
	awssdk "github.com/aws/aws-sdk-go-v2/aws"
	accessanalyzer "github.com/aws/aws-sdk-go-v2/service/accessanalyzer"
	account "github.com/aws/aws-sdk-go-v2/service/account"
	acm "github.com/aws/aws-sdk-go-v2/service/acm"
	acmpca "github.com/aws/aws-sdk-go-v2/service/acmpca"
	aiops "github.com/aws/aws-sdk-go-v2/service/aiops"
	amp "github.com/aws/aws-sdk-go-v2/service/amp"
	amplify "github.com/aws/aws-sdk-go-v2/service/amplify"
	amplifybackend "github.com/aws/aws-sdk-go-v2/service/amplifybackend"
	amplifyuibuilder "github.com/aws/aws-sdk-go-v2/service/amplifyuibuilder"
	apigateway "github.com/aws/aws-sdk-go-v2/service/apigateway"
	apigatewaymanagementapi "github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi"
	apigatewayv2 "github.com/aws/aws-sdk-go-v2/service/apigatewayv2"
	appconfig "github.com/aws/aws-sdk-go-v2/service/appconfig"
	appconfigdata "github.com/aws/aws-sdk-go-v2/service/appconfigdata"
	appfabric "github.com/aws/aws-sdk-go-v2/service/appfabric"
	appflow "github.com/aws/aws-sdk-go-v2/service/appflow"
	appintegrations "github.com/aws/aws-sdk-go-v2/service/appintegrations"
	applicationautoscaling "github.com/aws/aws-sdk-go-v2/service/applicationautoscaling"
	applicationcostprofiler "github.com/aws/aws-sdk-go-v2/service/applicationcostprofiler"
	applicationdiscoveryservice "github.com/aws/aws-sdk-go-v2/service/applicationdiscoveryservice"
	applicationinsights "github.com/aws/aws-sdk-go-v2/service/applicationinsights"
	applicationsignals "github.com/aws/aws-sdk-go-v2/service/applicationsignals"
	appmesh "github.com/aws/aws-sdk-go-v2/service/appmesh"
	apprunner "github.com/aws/aws-sdk-go-v2/service/apprunner"
	appstream "github.com/aws/aws-sdk-go-v2/service/appstream"
	appsync "github.com/aws/aws-sdk-go-v2/service/appsync"
	arcregionswitch "github.com/aws/aws-sdk-go-v2/service/arcregionswitch"
	arczonalshift "github.com/aws/aws-sdk-go-v2/service/arczonalshift"
	artifact "github.com/aws/aws-sdk-go-v2/service/artifact"
	athena "github.com/aws/aws-sdk-go-v2/service/athena"
	auditmanager "github.com/aws/aws-sdk-go-v2/service/auditmanager"
	autoscaling "github.com/aws/aws-sdk-go-v2/service/autoscaling"
	autoscalingplans "github.com/aws/aws-sdk-go-v2/service/autoscalingplans"
	b2bi "github.com/aws/aws-sdk-go-v2/service/b2bi"
	backup "github.com/aws/aws-sdk-go-v2/service/backup"
	backupgateway "github.com/aws/aws-sdk-go-v2/service/backupgateway"
	backupsearch "github.com/aws/aws-sdk-go-v2/service/backupsearch"
	batch "github.com/aws/aws-sdk-go-v2/service/batch"
	bcmdashboards "github.com/aws/aws-sdk-go-v2/service/bcmdashboards"
	bcmdataexports "github.com/aws/aws-sdk-go-v2/service/bcmdataexports"
	bcmpricingcalculator "github.com/aws/aws-sdk-go-v2/service/bcmpricingcalculator"
	bcmrecommendedactions "github.com/aws/aws-sdk-go-v2/service/bcmrecommendedactions"
	bedrock "github.com/aws/aws-sdk-go-v2/service/bedrock"
	bedrockagent "github.com/aws/aws-sdk-go-v2/service/bedrockagent"
	bedrockagentcore "github.com/aws/aws-sdk-go-v2/service/bedrockagentcore"
	bedrockagentcorecontrol "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	bedrockagentruntime "github.com/aws/aws-sdk-go-v2/service/bedrockagentruntime"
	bedrockdataautomation "github.com/aws/aws-sdk-go-v2/service/bedrockdataautomation"
	bedrockdataautomationruntime "github.com/aws/aws-sdk-go-v2/service/bedrockdataautomationruntime"
	bedrockruntime "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
	billing "github.com/aws/aws-sdk-go-v2/service/billing"
	billingconductor "github.com/aws/aws-sdk-go-v2/service/billingconductor"
	braket "github.com/aws/aws-sdk-go-v2/service/braket"
	budgets "github.com/aws/aws-sdk-go-v2/service/budgets"
	chatbot "github.com/aws/aws-sdk-go-v2/service/chatbot"
	chime "github.com/aws/aws-sdk-go-v2/service/chime"
	chimesdkidentity "github.com/aws/aws-sdk-go-v2/service/chimesdkidentity"
	chimesdkmediapipelines "github.com/aws/aws-sdk-go-v2/service/chimesdkmediapipelines"
	chimesdkmeetings "github.com/aws/aws-sdk-go-v2/service/chimesdkmeetings"
	chimesdkmessaging "github.com/aws/aws-sdk-go-v2/service/chimesdkmessaging"
	chimesdkvoice "github.com/aws/aws-sdk-go-v2/service/chimesdkvoice"
	cleanrooms "github.com/aws/aws-sdk-go-v2/service/cleanrooms"
	cleanroomsml "github.com/aws/aws-sdk-go-v2/service/cleanroomsml"
	cloud9 "github.com/aws/aws-sdk-go-v2/service/cloud9"
	cloudcontrol "github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	clouddirectory "github.com/aws/aws-sdk-go-v2/service/clouddirectory"
	cloudformation "github.com/aws/aws-sdk-go-v2/service/cloudformation"
	cloudfront "github.com/aws/aws-sdk-go-v2/service/cloudfront"
	cloudfrontkeyvaluestore "github.com/aws/aws-sdk-go-v2/service/cloudfrontkeyvaluestore"
	cloudhsm "github.com/aws/aws-sdk-go-v2/service/cloudhsm"
	cloudhsmv2 "github.com/aws/aws-sdk-go-v2/service/cloudhsmv2"
	cloudsearch "github.com/aws/aws-sdk-go-v2/service/cloudsearch"
	cloudsearchdomain "github.com/aws/aws-sdk-go-v2/service/cloudsearchdomain"
	cloudtrail "github.com/aws/aws-sdk-go-v2/service/cloudtrail"
	cloudtraildata "github.com/aws/aws-sdk-go-v2/service/cloudtraildata"
	cloudwatch "github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	cloudwatchevents "github.com/aws/aws-sdk-go-v2/service/cloudwatchevents"
	cloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	codeartifact "github.com/aws/aws-sdk-go-v2/service/codeartifact"
	codebuild "github.com/aws/aws-sdk-go-v2/service/codebuild"
	codecatalyst "github.com/aws/aws-sdk-go-v2/service/codecatalyst"
	codecommit "github.com/aws/aws-sdk-go-v2/service/codecommit"
	codeconnections "github.com/aws/aws-sdk-go-v2/service/codeconnections"
	codedeploy "github.com/aws/aws-sdk-go-v2/service/codedeploy"
	codeguruprofiler "github.com/aws/aws-sdk-go-v2/service/codeguruprofiler"
	codegurureviewer "github.com/aws/aws-sdk-go-v2/service/codegurureviewer"
	codegurusecurity "github.com/aws/aws-sdk-go-v2/service/codegurusecurity"
	codepipeline "github.com/aws/aws-sdk-go-v2/service/codepipeline"
	codestarconnections "github.com/aws/aws-sdk-go-v2/service/codestarconnections"
	codestarnotifications "github.com/aws/aws-sdk-go-v2/service/codestarnotifications"
	cognitoidentity "github.com/aws/aws-sdk-go-v2/service/cognitoidentity"
	cognitoidentityprovider "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	cognitosync "github.com/aws/aws-sdk-go-v2/service/cognitosync"
	comprehend "github.com/aws/aws-sdk-go-v2/service/comprehend"
	comprehendmedical "github.com/aws/aws-sdk-go-v2/service/comprehendmedical"
	computeoptimizer "github.com/aws/aws-sdk-go-v2/service/computeoptimizer"
	computeoptimizerautomation "github.com/aws/aws-sdk-go-v2/service/computeoptimizerautomation"
	configservice "github.com/aws/aws-sdk-go-v2/service/configservice"
	connect "github.com/aws/aws-sdk-go-v2/service/connect"
	connectcampaigns "github.com/aws/aws-sdk-go-v2/service/connectcampaigns"
	connectcampaignsv2 "github.com/aws/aws-sdk-go-v2/service/connectcampaignsv2"
	connectcases "github.com/aws/aws-sdk-go-v2/service/connectcases"
	connectcontactlens "github.com/aws/aws-sdk-go-v2/service/connectcontactlens"
	connecthealth "github.com/aws/aws-sdk-go-v2/service/connecthealth"
	connectparticipant "github.com/aws/aws-sdk-go-v2/service/connectparticipant"
	controlcatalog "github.com/aws/aws-sdk-go-v2/service/controlcatalog"
	controltower "github.com/aws/aws-sdk-go-v2/service/controltower"
	costandusagereportservice "github.com/aws/aws-sdk-go-v2/service/costandusagereportservice"
	costexplorer "github.com/aws/aws-sdk-go-v2/service/costexplorer"
	costoptimizationhub "github.com/aws/aws-sdk-go-v2/service/costoptimizationhub"
	customerprofiles "github.com/aws/aws-sdk-go-v2/service/customerprofiles"
	databasemigrationservice "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	databrew "github.com/aws/aws-sdk-go-v2/service/databrew"
	dataexchange "github.com/aws/aws-sdk-go-v2/service/dataexchange"
	datapipeline "github.com/aws/aws-sdk-go-v2/service/datapipeline"
	datasync "github.com/aws/aws-sdk-go-v2/service/datasync"
	datazone "github.com/aws/aws-sdk-go-v2/service/datazone"
	dax "github.com/aws/aws-sdk-go-v2/service/dax"
	deadline "github.com/aws/aws-sdk-go-v2/service/deadline"
	detective "github.com/aws/aws-sdk-go-v2/service/detective"
	devicefarm "github.com/aws/aws-sdk-go-v2/service/devicefarm"
	devopsagent "github.com/aws/aws-sdk-go-v2/service/devopsagent"
	devopsguru "github.com/aws/aws-sdk-go-v2/service/devopsguru"
	directconnect "github.com/aws/aws-sdk-go-v2/service/directconnect"
	directoryservice "github.com/aws/aws-sdk-go-v2/service/directoryservice"
	directoryservicedata "github.com/aws/aws-sdk-go-v2/service/directoryservicedata"
	dlm "github.com/aws/aws-sdk-go-v2/service/dlm"
	docdb "github.com/aws/aws-sdk-go-v2/service/docdb"
	docdbelastic "github.com/aws/aws-sdk-go-v2/service/docdbelastic"
	drs "github.com/aws/aws-sdk-go-v2/service/drs"
	dsql "github.com/aws/aws-sdk-go-v2/service/dsql"
	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	dynamodbstreams "github.com/aws/aws-sdk-go-v2/service/dynamodbstreams"
	ebs "github.com/aws/aws-sdk-go-v2/service/ebs"
	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	ec2instanceconnect "github.com/aws/aws-sdk-go-v2/service/ec2instanceconnect"
	ecr "github.com/aws/aws-sdk-go-v2/service/ecr"
	ecrpublic "github.com/aws/aws-sdk-go-v2/service/ecrpublic"
	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	efs "github.com/aws/aws-sdk-go-v2/service/efs"
	eks "github.com/aws/aws-sdk-go-v2/service/eks"
	eksauth "github.com/aws/aws-sdk-go-v2/service/eksauth"
	elasticache "github.com/aws/aws-sdk-go-v2/service/elasticache"
	elasticbeanstalk "github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk"
	elasticloadbalancing "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancing"
	elasticloadbalancingv2 "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	elasticsearchservice "github.com/aws/aws-sdk-go-v2/service/elasticsearchservice"
	elementalinference "github.com/aws/aws-sdk-go-v2/service/elementalinference"
	emr "github.com/aws/aws-sdk-go-v2/service/emr"
	emrcontainers "github.com/aws/aws-sdk-go-v2/service/emrcontainers"
	emrserverless "github.com/aws/aws-sdk-go-v2/service/emrserverless"
	entityresolution "github.com/aws/aws-sdk-go-v2/service/entityresolution"
	eventbridge "github.com/aws/aws-sdk-go-v2/service/eventbridge"
	evs "github.com/aws/aws-sdk-go-v2/service/evs"
	finspace "github.com/aws/aws-sdk-go-v2/service/finspace"
	finspacedata "github.com/aws/aws-sdk-go-v2/service/finspacedata"
	firehose "github.com/aws/aws-sdk-go-v2/service/firehose"
	fis "github.com/aws/aws-sdk-go-v2/service/fis"
	fms "github.com/aws/aws-sdk-go-v2/service/fms"
	forecast "github.com/aws/aws-sdk-go-v2/service/forecast"
	forecastquery "github.com/aws/aws-sdk-go-v2/service/forecastquery"
	frauddetector "github.com/aws/aws-sdk-go-v2/service/frauddetector"
	freetier "github.com/aws/aws-sdk-go-v2/service/freetier"
	fsx "github.com/aws/aws-sdk-go-v2/service/fsx"
	gamelift "github.com/aws/aws-sdk-go-v2/service/gamelift"
	gameliftstreams "github.com/aws/aws-sdk-go-v2/service/gameliftstreams"
	geomaps "github.com/aws/aws-sdk-go-v2/service/geomaps"
	geoplaces "github.com/aws/aws-sdk-go-v2/service/geoplaces"
	georoutes "github.com/aws/aws-sdk-go-v2/service/georoutes"
	glacier "github.com/aws/aws-sdk-go-v2/service/glacier"
	globalaccelerator "github.com/aws/aws-sdk-go-v2/service/globalaccelerator"
	glue "github.com/aws/aws-sdk-go-v2/service/glue"
	grafana "github.com/aws/aws-sdk-go-v2/service/grafana"
	greengrass "github.com/aws/aws-sdk-go-v2/service/greengrass"
	greengrassv2 "github.com/aws/aws-sdk-go-v2/service/greengrassv2"
	groundstation "github.com/aws/aws-sdk-go-v2/service/groundstation"
	guardduty "github.com/aws/aws-sdk-go-v2/service/guardduty"
	health "github.com/aws/aws-sdk-go-v2/service/health"
	healthlake "github.com/aws/aws-sdk-go-v2/service/healthlake"
	iam "github.com/aws/aws-sdk-go-v2/service/iam"
	identitystore "github.com/aws/aws-sdk-go-v2/service/identitystore"
	imagebuilder "github.com/aws/aws-sdk-go-v2/service/imagebuilder"
	inspector "github.com/aws/aws-sdk-go-v2/service/inspector"
	inspector2 "github.com/aws/aws-sdk-go-v2/service/inspector2"
	inspectorscan "github.com/aws/aws-sdk-go-v2/service/inspectorscan"
	interconnect "github.com/aws/aws-sdk-go-v2/service/interconnect"
	internetmonitor "github.com/aws/aws-sdk-go-v2/service/internetmonitor"
	invoicing "github.com/aws/aws-sdk-go-v2/service/invoicing"
	iot "github.com/aws/aws-sdk-go-v2/service/iot"
	iotdataplane "github.com/aws/aws-sdk-go-v2/service/iotdataplane"
	iotdeviceadvisor "github.com/aws/aws-sdk-go-v2/service/iotdeviceadvisor"
	iotfleetwise "github.com/aws/aws-sdk-go-v2/service/iotfleetwise"
	iotjobsdataplane "github.com/aws/aws-sdk-go-v2/service/iotjobsdataplane"
	iotmanagedintegrations "github.com/aws/aws-sdk-go-v2/service/iotmanagedintegrations"
	iotsecuretunneling "github.com/aws/aws-sdk-go-v2/service/iotsecuretunneling"
	iotsitewise "github.com/aws/aws-sdk-go-v2/service/iotsitewise"
	iotthingsgraph "github.com/aws/aws-sdk-go-v2/service/iotthingsgraph"
	iottwinmaker "github.com/aws/aws-sdk-go-v2/service/iottwinmaker"
	iotwireless "github.com/aws/aws-sdk-go-v2/service/iotwireless"
	ivs "github.com/aws/aws-sdk-go-v2/service/ivs"
	ivschat "github.com/aws/aws-sdk-go-v2/service/ivschat"
	ivsrealtime "github.com/aws/aws-sdk-go-v2/service/ivsrealtime"
	kafka "github.com/aws/aws-sdk-go-v2/service/kafka"
	kafkaconnect "github.com/aws/aws-sdk-go-v2/service/kafkaconnect"
	kendra "github.com/aws/aws-sdk-go-v2/service/kendra"
	kendraranking "github.com/aws/aws-sdk-go-v2/service/kendraranking"
	keyspaces "github.com/aws/aws-sdk-go-v2/service/keyspaces"
	keyspacesstreams "github.com/aws/aws-sdk-go-v2/service/keyspacesstreams"
	kinesis "github.com/aws/aws-sdk-go-v2/service/kinesis"
	kinesisanalytics "github.com/aws/aws-sdk-go-v2/service/kinesisanalytics"
	kinesisanalyticsv2 "github.com/aws/aws-sdk-go-v2/service/kinesisanalyticsv2"
	kinesisvideo "github.com/aws/aws-sdk-go-v2/service/kinesisvideo"
	kinesisvideoarchivedmedia "github.com/aws/aws-sdk-go-v2/service/kinesisvideoarchivedmedia"
	kinesisvideomedia "github.com/aws/aws-sdk-go-v2/service/kinesisvideomedia"
	kinesisvideosignaling "github.com/aws/aws-sdk-go-v2/service/kinesisvideosignaling"
	kinesisvideowebrtcstorage "github.com/aws/aws-sdk-go-v2/service/kinesisvideowebrtcstorage"
	kms "github.com/aws/aws-sdk-go-v2/service/kms"
	lakeformation "github.com/aws/aws-sdk-go-v2/service/lakeformation"
	lambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	lambdacore "github.com/aws/aws-sdk-go-v2/service/lambdacore"
	lambdamicrovms "github.com/aws/aws-sdk-go-v2/service/lambdamicrovms"
	launchwizard "github.com/aws/aws-sdk-go-v2/service/launchwizard"
	lexmodelbuildingservice "github.com/aws/aws-sdk-go-v2/service/lexmodelbuildingservice"
	lexmodelsv2 "github.com/aws/aws-sdk-go-v2/service/lexmodelsv2"
	lexruntimeservice "github.com/aws/aws-sdk-go-v2/service/lexruntimeservice"
	lexruntimev2 "github.com/aws/aws-sdk-go-v2/service/lexruntimev2"
	licensemanager "github.com/aws/aws-sdk-go-v2/service/licensemanager"
	licensemanagerlinuxsubscriptions "github.com/aws/aws-sdk-go-v2/service/licensemanagerlinuxsubscriptions"
	licensemanagerusersubscriptions "github.com/aws/aws-sdk-go-v2/service/licensemanagerusersubscriptions"
	lightsail "github.com/aws/aws-sdk-go-v2/service/lightsail"
	location "github.com/aws/aws-sdk-go-v2/service/location"
	lookoutequipment "github.com/aws/aws-sdk-go-v2/service/lookoutequipment"
	m2 "github.com/aws/aws-sdk-go-v2/service/m2"
	machinelearning "github.com/aws/aws-sdk-go-v2/service/machinelearning"
	macie2 "github.com/aws/aws-sdk-go-v2/service/macie2"
	mailmanager "github.com/aws/aws-sdk-go-v2/service/mailmanager"
	managedblockchain "github.com/aws/aws-sdk-go-v2/service/managedblockchain"
	managedblockchainquery "github.com/aws/aws-sdk-go-v2/service/managedblockchainquery"
	marketplaceagreement "github.com/aws/aws-sdk-go-v2/service/marketplaceagreement"
	marketplacecatalog "github.com/aws/aws-sdk-go-v2/service/marketplacecatalog"
	marketplacecommerceanalytics "github.com/aws/aws-sdk-go-v2/service/marketplacecommerceanalytics"
	marketplacedeployment "github.com/aws/aws-sdk-go-v2/service/marketplacedeployment"
	marketplacediscovery "github.com/aws/aws-sdk-go-v2/service/marketplacediscovery"
	marketplaceentitlementservice "github.com/aws/aws-sdk-go-v2/service/marketplaceentitlementservice"
	marketplacemetering "github.com/aws/aws-sdk-go-v2/service/marketplacemetering"
	marketplacereporting "github.com/aws/aws-sdk-go-v2/service/marketplacereporting"
	mediaconnect "github.com/aws/aws-sdk-go-v2/service/mediaconnect"
	mediaconvert "github.com/aws/aws-sdk-go-v2/service/mediaconvert"
	medialive "github.com/aws/aws-sdk-go-v2/service/medialive"
	mediapackage "github.com/aws/aws-sdk-go-v2/service/mediapackage"
	mediapackagev2 "github.com/aws/aws-sdk-go-v2/service/mediapackagev2"
	mediapackagevod "github.com/aws/aws-sdk-go-v2/service/mediapackagevod"
	mediastore "github.com/aws/aws-sdk-go-v2/service/mediastore"
	mediastoredata "github.com/aws/aws-sdk-go-v2/service/mediastoredata"
	mediatailor "github.com/aws/aws-sdk-go-v2/service/mediatailor"
	medicalimaging "github.com/aws/aws-sdk-go-v2/service/medicalimaging"
	memorydb "github.com/aws/aws-sdk-go-v2/service/memorydb"
	mgn "github.com/aws/aws-sdk-go-v2/service/mgn"
	migrationhub "github.com/aws/aws-sdk-go-v2/service/migrationhub"
	migrationhubconfig "github.com/aws/aws-sdk-go-v2/service/migrationhubconfig"
	migrationhuborchestrator "github.com/aws/aws-sdk-go-v2/service/migrationhuborchestrator"
	migrationhubrefactorspaces "github.com/aws/aws-sdk-go-v2/service/migrationhubrefactorspaces"
	migrationhubstrategy "github.com/aws/aws-sdk-go-v2/service/migrationhubstrategy"
	mpa "github.com/aws/aws-sdk-go-v2/service/mpa"
	mq "github.com/aws/aws-sdk-go-v2/service/mq"
	mturk "github.com/aws/aws-sdk-go-v2/service/mturk"
	mwaa "github.com/aws/aws-sdk-go-v2/service/mwaa"
	mwaaserverless "github.com/aws/aws-sdk-go-v2/service/mwaaserverless"
	neptune "github.com/aws/aws-sdk-go-v2/service/neptune"
	neptunedata "github.com/aws/aws-sdk-go-v2/service/neptunedata"
	neptunegraph "github.com/aws/aws-sdk-go-v2/service/neptunegraph"
	networkfirewall "github.com/aws/aws-sdk-go-v2/service/networkfirewall"
	networkflowmonitor "github.com/aws/aws-sdk-go-v2/service/networkflowmonitor"
	networkmanager "github.com/aws/aws-sdk-go-v2/service/networkmanager"
	networkmonitor "github.com/aws/aws-sdk-go-v2/service/networkmonitor"
	notifications "github.com/aws/aws-sdk-go-v2/service/notifications"
	notificationscontacts "github.com/aws/aws-sdk-go-v2/service/notificationscontacts"
	novaact "github.com/aws/aws-sdk-go-v2/service/novaact"
	oam "github.com/aws/aws-sdk-go-v2/service/oam"
	observabilityadmin "github.com/aws/aws-sdk-go-v2/service/observabilityadmin"
	odb "github.com/aws/aws-sdk-go-v2/service/odb"
	omics "github.com/aws/aws-sdk-go-v2/service/omics"
	opensearch "github.com/aws/aws-sdk-go-v2/service/opensearch"
	opensearchserverless "github.com/aws/aws-sdk-go-v2/service/opensearchserverless"
	organizations "github.com/aws/aws-sdk-go-v2/service/organizations"
	osis "github.com/aws/aws-sdk-go-v2/service/osis"
	outposts "github.com/aws/aws-sdk-go-v2/service/outposts"
	partnercentralaccount "github.com/aws/aws-sdk-go-v2/service/partnercentralaccount"
	partnercentralbenefits "github.com/aws/aws-sdk-go-v2/service/partnercentralbenefits"
	partnercentralchannel "github.com/aws/aws-sdk-go-v2/service/partnercentralchannel"
	partnercentralselling "github.com/aws/aws-sdk-go-v2/service/partnercentralselling"
	paymentcryptography "github.com/aws/aws-sdk-go-v2/service/paymentcryptography"
	paymentcryptographydata "github.com/aws/aws-sdk-go-v2/service/paymentcryptographydata"
	pcaconnectorad "github.com/aws/aws-sdk-go-v2/service/pcaconnectorad"
	pcaconnectorscep "github.com/aws/aws-sdk-go-v2/service/pcaconnectorscep"
	pcs "github.com/aws/aws-sdk-go-v2/service/pcs"
	personalize "github.com/aws/aws-sdk-go-v2/service/personalize"
	personalizeevents "github.com/aws/aws-sdk-go-v2/service/personalizeevents"
	personalizeruntime "github.com/aws/aws-sdk-go-v2/service/personalizeruntime"
	pi "github.com/aws/aws-sdk-go-v2/service/pi"
	pinpoint "github.com/aws/aws-sdk-go-v2/service/pinpoint"
	pinpointemail "github.com/aws/aws-sdk-go-v2/service/pinpointemail"
	pinpointsmsvoice "github.com/aws/aws-sdk-go-v2/service/pinpointsmsvoice"
	pinpointsmsvoicev2 "github.com/aws/aws-sdk-go-v2/service/pinpointsmsvoicev2"
	pipes "github.com/aws/aws-sdk-go-v2/service/pipes"
	polly "github.com/aws/aws-sdk-go-v2/service/polly"
	pricing "github.com/aws/aws-sdk-go-v2/service/pricing"
	proton "github.com/aws/aws-sdk-go-v2/service/proton"
	qapps "github.com/aws/aws-sdk-go-v2/service/qapps"
	qbusiness "github.com/aws/aws-sdk-go-v2/service/qbusiness"
	qconnect "github.com/aws/aws-sdk-go-v2/service/qconnect"
	quicksight "github.com/aws/aws-sdk-go-v2/service/quicksight"
	ram "github.com/aws/aws-sdk-go-v2/service/ram"
	rbin "github.com/aws/aws-sdk-go-v2/service/rbin"
	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	rdsdata "github.com/aws/aws-sdk-go-v2/service/rdsdata"
	redshift "github.com/aws/aws-sdk-go-v2/service/redshift"
	redshiftdata "github.com/aws/aws-sdk-go-v2/service/redshiftdata"
	redshiftserverless "github.com/aws/aws-sdk-go-v2/service/redshiftserverless"
	rekognition "github.com/aws/aws-sdk-go-v2/service/rekognition"
	repostspace "github.com/aws/aws-sdk-go-v2/service/repostspace"
	resiliencehub "github.com/aws/aws-sdk-go-v2/service/resiliencehub"
	resiliencehubv2 "github.com/aws/aws-sdk-go-v2/service/resiliencehubv2"
	resourceexplorer2 "github.com/aws/aws-sdk-go-v2/service/resourceexplorer2"
	resourcegroups "github.com/aws/aws-sdk-go-v2/service/resourcegroups"
	resourcegroupstaggingapi "github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi"
	rolesanywhere "github.com/aws/aws-sdk-go-v2/service/rolesanywhere"
	route53 "github.com/aws/aws-sdk-go-v2/service/route53"
	route53domains "github.com/aws/aws-sdk-go-v2/service/route53domains"
	route53globalresolver "github.com/aws/aws-sdk-go-v2/service/route53globalresolver"
	route53profiles "github.com/aws/aws-sdk-go-v2/service/route53profiles"
	route53recoverycluster "github.com/aws/aws-sdk-go-v2/service/route53recoverycluster"
	route53recoverycontrolconfig "github.com/aws/aws-sdk-go-v2/service/route53recoverycontrolconfig"
	route53recoveryreadiness "github.com/aws/aws-sdk-go-v2/service/route53recoveryreadiness"
	route53resolver "github.com/aws/aws-sdk-go-v2/service/route53resolver"
	rtbfabric "github.com/aws/aws-sdk-go-v2/service/rtbfabric"
	rum "github.com/aws/aws-sdk-go-v2/service/rum"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	s3control "github.com/aws/aws-sdk-go-v2/service/s3control"
	s3files "github.com/aws/aws-sdk-go-v2/service/s3files"
	s3outposts "github.com/aws/aws-sdk-go-v2/service/s3outposts"
	s3tables "github.com/aws/aws-sdk-go-v2/service/s3tables"
	s3vectors "github.com/aws/aws-sdk-go-v2/service/s3vectors"
	sagemaker "github.com/aws/aws-sdk-go-v2/service/sagemaker"
	sagemakera2iruntime "github.com/aws/aws-sdk-go-v2/service/sagemakera2iruntime"
	sagemakeredge "github.com/aws/aws-sdk-go-v2/service/sagemakeredge"
	sagemakerfeaturestoreruntime "github.com/aws/aws-sdk-go-v2/service/sagemakerfeaturestoreruntime"
	sagemakergeospatial "github.com/aws/aws-sdk-go-v2/service/sagemakergeospatial"
	sagemakerjobruntime "github.com/aws/aws-sdk-go-v2/service/sagemakerjobruntime"
	sagemakermetrics "github.com/aws/aws-sdk-go-v2/service/sagemakermetrics"
	sagemakerruntime "github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
	sagemakerruntimehttp2 "github.com/aws/aws-sdk-go-v2/service/sagemakerruntimehttp2"
	savingsplans "github.com/aws/aws-sdk-go-v2/service/savingsplans"
	scheduler "github.com/aws/aws-sdk-go-v2/service/scheduler"
	schemas "github.com/aws/aws-sdk-go-v2/service/schemas"
	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	securityagent "github.com/aws/aws-sdk-go-v2/service/securityagent"
	securityhub "github.com/aws/aws-sdk-go-v2/service/securityhub"
	securityir "github.com/aws/aws-sdk-go-v2/service/securityir"
	securitylake "github.com/aws/aws-sdk-go-v2/service/securitylake"
	serverlessapplicationrepository "github.com/aws/aws-sdk-go-v2/service/serverlessapplicationrepository"
	servicecatalog "github.com/aws/aws-sdk-go-v2/service/servicecatalog"
	servicecatalogappregistry "github.com/aws/aws-sdk-go-v2/service/servicecatalogappregistry"
	servicediscovery "github.com/aws/aws-sdk-go-v2/service/servicediscovery"
	servicequotas "github.com/aws/aws-sdk-go-v2/service/servicequotas"
	ses "github.com/aws/aws-sdk-go-v2/service/ses"
	sesv2 "github.com/aws/aws-sdk-go-v2/service/sesv2"
	sfn "github.com/aws/aws-sdk-go-v2/service/sfn"
	shield "github.com/aws/aws-sdk-go-v2/service/shield"
	signer "github.com/aws/aws-sdk-go-v2/service/signer"
	signerdata "github.com/aws/aws-sdk-go-v2/service/signerdata"
	signin "github.com/aws/aws-sdk-go-v2/service/signin"
	simpledbv2 "github.com/aws/aws-sdk-go-v2/service/simpledbv2"
	snowball "github.com/aws/aws-sdk-go-v2/service/snowball"
	snowdevicemanagement "github.com/aws/aws-sdk-go-v2/service/snowdevicemanagement"
	sns "github.com/aws/aws-sdk-go-v2/service/sns"
	socialmessaging "github.com/aws/aws-sdk-go-v2/service/socialmessaging"
	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	ssmcontacts "github.com/aws/aws-sdk-go-v2/service/ssmcontacts"
	ssmguiconnect "github.com/aws/aws-sdk-go-v2/service/ssmguiconnect"
	ssmincidents "github.com/aws/aws-sdk-go-v2/service/ssmincidents"
	ssmquicksetup "github.com/aws/aws-sdk-go-v2/service/ssmquicksetup"
	ssmsap "github.com/aws/aws-sdk-go-v2/service/ssmsap"
	sso "github.com/aws/aws-sdk-go-v2/service/sso"
	ssoadmin "github.com/aws/aws-sdk-go-v2/service/ssoadmin"
	ssooidc "github.com/aws/aws-sdk-go-v2/service/ssooidc"
	storagegateway "github.com/aws/aws-sdk-go-v2/service/storagegateway"
	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	supplychain "github.com/aws/aws-sdk-go-v2/service/supplychain"
	support "github.com/aws/aws-sdk-go-v2/service/support"
	supportapp "github.com/aws/aws-sdk-go-v2/service/supportapp"
	supportauthz "github.com/aws/aws-sdk-go-v2/service/supportauthz"
	sustainability "github.com/aws/aws-sdk-go-v2/service/sustainability"
	swf "github.com/aws/aws-sdk-go-v2/service/swf"
	synthetics "github.com/aws/aws-sdk-go-v2/service/synthetics"
	taxsettings "github.com/aws/aws-sdk-go-v2/service/taxsettings"
	textract "github.com/aws/aws-sdk-go-v2/service/textract"
	timestreaminfluxdb "github.com/aws/aws-sdk-go-v2/service/timestreaminfluxdb"
	timestreamquery "github.com/aws/aws-sdk-go-v2/service/timestreamquery"
	timestreamwrite "github.com/aws/aws-sdk-go-v2/service/timestreamwrite"
	tnb "github.com/aws/aws-sdk-go-v2/service/tnb"
	transcribe "github.com/aws/aws-sdk-go-v2/service/transcribe"
	transcribestreaming "github.com/aws/aws-sdk-go-v2/service/transcribestreaming"
	transfer "github.com/aws/aws-sdk-go-v2/service/transfer"
	translate "github.com/aws/aws-sdk-go-v2/service/translate"
	trustedadvisor "github.com/aws/aws-sdk-go-v2/service/trustedadvisor"
	uxc "github.com/aws/aws-sdk-go-v2/service/uxc"
	verifiedpermissions "github.com/aws/aws-sdk-go-v2/service/verifiedpermissions"
	voiceid "github.com/aws/aws-sdk-go-v2/service/voiceid"
	vpclattice "github.com/aws/aws-sdk-go-v2/service/vpclattice"
	waf "github.com/aws/aws-sdk-go-v2/service/waf"
	wafregional "github.com/aws/aws-sdk-go-v2/service/wafregional"
	wafv2 "github.com/aws/aws-sdk-go-v2/service/wafv2"
	wellarchitected "github.com/aws/aws-sdk-go-v2/service/wellarchitected"
	wickr "github.com/aws/aws-sdk-go-v2/service/wickr"
	wisdom "github.com/aws/aws-sdk-go-v2/service/wisdom"
	workdocs "github.com/aws/aws-sdk-go-v2/service/workdocs"
	workmail "github.com/aws/aws-sdk-go-v2/service/workmail"
	workmailmessageflow "github.com/aws/aws-sdk-go-v2/service/workmailmessageflow"
	workspaces "github.com/aws/aws-sdk-go-v2/service/workspaces"
	workspacesinstances "github.com/aws/aws-sdk-go-v2/service/workspacesinstances"
	workspacesthinclient "github.com/aws/aws-sdk-go-v2/service/workspacesthinclient"
	workspacesweb "github.com/aws/aws-sdk-go-v2/service/workspacesweb"
	xray "github.com/aws/aws-sdk-go-v2/service/xray"
)

// Factories maps every configured AWS service name to a constructor for its
// SDK client. Regenerate with: go run ./internal/gen/services (or
// "make generate") after editing services.json.
var Factories = map[string]ClientFactory{
	"accessanalyzer":                   func(cfg awssdk.Config) any { return accessanalyzer.NewFromConfig(cfg) },
	"account":                          func(cfg awssdk.Config) any { return account.NewFromConfig(cfg) },
	"acm":                              func(cfg awssdk.Config) any { return acm.NewFromConfig(cfg) },
	"acmpca":                           func(cfg awssdk.Config) any { return acmpca.NewFromConfig(cfg) },
	"aiops":                            func(cfg awssdk.Config) any { return aiops.NewFromConfig(cfg) },
	"amp":                              func(cfg awssdk.Config) any { return amp.NewFromConfig(cfg) },
	"amplify":                          func(cfg awssdk.Config) any { return amplify.NewFromConfig(cfg) },
	"amplifybackend":                   func(cfg awssdk.Config) any { return amplifybackend.NewFromConfig(cfg) },
	"amplifyuibuilder":                 func(cfg awssdk.Config) any { return amplifyuibuilder.NewFromConfig(cfg) },
	"apigateway":                       func(cfg awssdk.Config) any { return apigateway.NewFromConfig(cfg) },
	"apigatewaymanagementapi":          func(cfg awssdk.Config) any { return apigatewaymanagementapi.NewFromConfig(cfg) },
	"apigatewayv2":                     func(cfg awssdk.Config) any { return apigatewayv2.NewFromConfig(cfg) },
	"appconfig":                        func(cfg awssdk.Config) any { return appconfig.NewFromConfig(cfg) },
	"appconfigdata":                    func(cfg awssdk.Config) any { return appconfigdata.NewFromConfig(cfg) },
	"appfabric":                        func(cfg awssdk.Config) any { return appfabric.NewFromConfig(cfg) },
	"appflow":                          func(cfg awssdk.Config) any { return appflow.NewFromConfig(cfg) },
	"appintegrations":                  func(cfg awssdk.Config) any { return appintegrations.NewFromConfig(cfg) },
	"applicationautoscaling":           func(cfg awssdk.Config) any { return applicationautoscaling.NewFromConfig(cfg) },
	"applicationcostprofiler":          func(cfg awssdk.Config) any { return applicationcostprofiler.NewFromConfig(cfg) },
	"applicationdiscoveryservice":      func(cfg awssdk.Config) any { return applicationdiscoveryservice.NewFromConfig(cfg) },
	"applicationinsights":              func(cfg awssdk.Config) any { return applicationinsights.NewFromConfig(cfg) },
	"applicationsignals":               func(cfg awssdk.Config) any { return applicationsignals.NewFromConfig(cfg) },
	"appmesh":                          func(cfg awssdk.Config) any { return appmesh.NewFromConfig(cfg) },
	"apprunner":                        func(cfg awssdk.Config) any { return apprunner.NewFromConfig(cfg) },
	"appstream":                        func(cfg awssdk.Config) any { return appstream.NewFromConfig(cfg) },
	"appsync":                          func(cfg awssdk.Config) any { return appsync.NewFromConfig(cfg) },
	"arcregionswitch":                  func(cfg awssdk.Config) any { return arcregionswitch.NewFromConfig(cfg) },
	"arczonalshift":                    func(cfg awssdk.Config) any { return arczonalshift.NewFromConfig(cfg) },
	"artifact":                         func(cfg awssdk.Config) any { return artifact.NewFromConfig(cfg) },
	"athena":                           func(cfg awssdk.Config) any { return athena.NewFromConfig(cfg) },
	"auditmanager":                     func(cfg awssdk.Config) any { return auditmanager.NewFromConfig(cfg) },
	"autoscaling":                      func(cfg awssdk.Config) any { return autoscaling.NewFromConfig(cfg) },
	"autoscalingplans":                 func(cfg awssdk.Config) any { return autoscalingplans.NewFromConfig(cfg) },
	"b2bi":                             func(cfg awssdk.Config) any { return b2bi.NewFromConfig(cfg) },
	"backup":                           func(cfg awssdk.Config) any { return backup.NewFromConfig(cfg) },
	"backupgateway":                    func(cfg awssdk.Config) any { return backupgateway.NewFromConfig(cfg) },
	"backupsearch":                     func(cfg awssdk.Config) any { return backupsearch.NewFromConfig(cfg) },
	"batch":                            func(cfg awssdk.Config) any { return batch.NewFromConfig(cfg) },
	"bcmdashboards":                    func(cfg awssdk.Config) any { return bcmdashboards.NewFromConfig(cfg) },
	"bcmdataexports":                   func(cfg awssdk.Config) any { return bcmdataexports.NewFromConfig(cfg) },
	"bcmpricingcalculator":             func(cfg awssdk.Config) any { return bcmpricingcalculator.NewFromConfig(cfg) },
	"bcmrecommendedactions":            func(cfg awssdk.Config) any { return bcmrecommendedactions.NewFromConfig(cfg) },
	"bedrock":                          func(cfg awssdk.Config) any { return bedrock.NewFromConfig(cfg) },
	"bedrockagent":                     func(cfg awssdk.Config) any { return bedrockagent.NewFromConfig(cfg) },
	"bedrockagentcore":                 func(cfg awssdk.Config) any { return bedrockagentcore.NewFromConfig(cfg) },
	"bedrockagentcorecontrol":          func(cfg awssdk.Config) any { return bedrockagentcorecontrol.NewFromConfig(cfg) },
	"bedrockagentruntime":              func(cfg awssdk.Config) any { return bedrockagentruntime.NewFromConfig(cfg) },
	"bedrockdataautomation":            func(cfg awssdk.Config) any { return bedrockdataautomation.NewFromConfig(cfg) },
	"bedrockdataautomationruntime":     func(cfg awssdk.Config) any { return bedrockdataautomationruntime.NewFromConfig(cfg) },
	"bedrockruntime":                   func(cfg awssdk.Config) any { return bedrockruntime.NewFromConfig(cfg) },
	"billing":                          func(cfg awssdk.Config) any { return billing.NewFromConfig(cfg) },
	"billingconductor":                 func(cfg awssdk.Config) any { return billingconductor.NewFromConfig(cfg) },
	"braket":                           func(cfg awssdk.Config) any { return braket.NewFromConfig(cfg) },
	"budgets":                          func(cfg awssdk.Config) any { return budgets.NewFromConfig(cfg) },
	"chatbot":                          func(cfg awssdk.Config) any { return chatbot.NewFromConfig(cfg) },
	"chime":                            func(cfg awssdk.Config) any { return chime.NewFromConfig(cfg) },
	"chimesdkidentity":                 func(cfg awssdk.Config) any { return chimesdkidentity.NewFromConfig(cfg) },
	"chimesdkmediapipelines":           func(cfg awssdk.Config) any { return chimesdkmediapipelines.NewFromConfig(cfg) },
	"chimesdkmeetings":                 func(cfg awssdk.Config) any { return chimesdkmeetings.NewFromConfig(cfg) },
	"chimesdkmessaging":                func(cfg awssdk.Config) any { return chimesdkmessaging.NewFromConfig(cfg) },
	"chimesdkvoice":                    func(cfg awssdk.Config) any { return chimesdkvoice.NewFromConfig(cfg) },
	"cleanrooms":                       func(cfg awssdk.Config) any { return cleanrooms.NewFromConfig(cfg) },
	"cleanroomsml":                     func(cfg awssdk.Config) any { return cleanroomsml.NewFromConfig(cfg) },
	"cloud9":                           func(cfg awssdk.Config) any { return cloud9.NewFromConfig(cfg) },
	"cloudcontrol":                     func(cfg awssdk.Config) any { return cloudcontrol.NewFromConfig(cfg) },
	"clouddirectory":                   func(cfg awssdk.Config) any { return clouddirectory.NewFromConfig(cfg) },
	"cloudformation":                   func(cfg awssdk.Config) any { return cloudformation.NewFromConfig(cfg) },
	"cloudfront":                       func(cfg awssdk.Config) any { return cloudfront.NewFromConfig(cfg) },
	"cloudfrontkeyvaluestore":          func(cfg awssdk.Config) any { return cloudfrontkeyvaluestore.NewFromConfig(cfg) },
	"cloudhsm":                         func(cfg awssdk.Config) any { return cloudhsm.NewFromConfig(cfg) },
	"cloudhsmv2":                       func(cfg awssdk.Config) any { return cloudhsmv2.NewFromConfig(cfg) },
	"cloudsearch":                      func(cfg awssdk.Config) any { return cloudsearch.NewFromConfig(cfg) },
	"cloudsearchdomain":                func(cfg awssdk.Config) any { return cloudsearchdomain.NewFromConfig(cfg) },
	"cloudtrail":                       func(cfg awssdk.Config) any { return cloudtrail.NewFromConfig(cfg) },
	"cloudtraildata":                   func(cfg awssdk.Config) any { return cloudtraildata.NewFromConfig(cfg) },
	"cloudwatch":                       func(cfg awssdk.Config) any { return cloudwatch.NewFromConfig(cfg) },
	"cloudwatchevents":                 func(cfg awssdk.Config) any { return cloudwatchevents.NewFromConfig(cfg) },
	"cloudwatchlogs":                   func(cfg awssdk.Config) any { return cloudwatchlogs.NewFromConfig(cfg) },
	"codeartifact":                     func(cfg awssdk.Config) any { return codeartifact.NewFromConfig(cfg) },
	"codebuild":                        func(cfg awssdk.Config) any { return codebuild.NewFromConfig(cfg) },
	"codecatalyst":                     func(cfg awssdk.Config) any { return codecatalyst.NewFromConfig(cfg) },
	"codecommit":                       func(cfg awssdk.Config) any { return codecommit.NewFromConfig(cfg) },
	"codeconnections":                  func(cfg awssdk.Config) any { return codeconnections.NewFromConfig(cfg) },
	"codedeploy":                       func(cfg awssdk.Config) any { return codedeploy.NewFromConfig(cfg) },
	"codeguruprofiler":                 func(cfg awssdk.Config) any { return codeguruprofiler.NewFromConfig(cfg) },
	"codegurureviewer":                 func(cfg awssdk.Config) any { return codegurureviewer.NewFromConfig(cfg) },
	"codegurusecurity":                 func(cfg awssdk.Config) any { return codegurusecurity.NewFromConfig(cfg) },
	"codepipeline":                     func(cfg awssdk.Config) any { return codepipeline.NewFromConfig(cfg) },
	"codestarconnections":              func(cfg awssdk.Config) any { return codestarconnections.NewFromConfig(cfg) },
	"codestarnotifications":            func(cfg awssdk.Config) any { return codestarnotifications.NewFromConfig(cfg) },
	"cognitoidentity":                  func(cfg awssdk.Config) any { return cognitoidentity.NewFromConfig(cfg) },
	"cognitoidentityprovider":          func(cfg awssdk.Config) any { return cognitoidentityprovider.NewFromConfig(cfg) },
	"cognitosync":                      func(cfg awssdk.Config) any { return cognitosync.NewFromConfig(cfg) },
	"comprehend":                       func(cfg awssdk.Config) any { return comprehend.NewFromConfig(cfg) },
	"comprehendmedical":                func(cfg awssdk.Config) any { return comprehendmedical.NewFromConfig(cfg) },
	"computeoptimizer":                 func(cfg awssdk.Config) any { return computeoptimizer.NewFromConfig(cfg) },
	"computeoptimizerautomation":       func(cfg awssdk.Config) any { return computeoptimizerautomation.NewFromConfig(cfg) },
	"configservice":                    func(cfg awssdk.Config) any { return configservice.NewFromConfig(cfg) },
	"connect":                          func(cfg awssdk.Config) any { return connect.NewFromConfig(cfg) },
	"connectcampaigns":                 func(cfg awssdk.Config) any { return connectcampaigns.NewFromConfig(cfg) },
	"connectcampaignsv2":               func(cfg awssdk.Config) any { return connectcampaignsv2.NewFromConfig(cfg) },
	"connectcases":                     func(cfg awssdk.Config) any { return connectcases.NewFromConfig(cfg) },
	"connectcontactlens":               func(cfg awssdk.Config) any { return connectcontactlens.NewFromConfig(cfg) },
	"connecthealth":                    func(cfg awssdk.Config) any { return connecthealth.NewFromConfig(cfg) },
	"connectparticipant":               func(cfg awssdk.Config) any { return connectparticipant.NewFromConfig(cfg) },
	"controlcatalog":                   func(cfg awssdk.Config) any { return controlcatalog.NewFromConfig(cfg) },
	"controltower":                     func(cfg awssdk.Config) any { return controltower.NewFromConfig(cfg) },
	"costandusagereportservice":        func(cfg awssdk.Config) any { return costandusagereportservice.NewFromConfig(cfg) },
	"costexplorer":                     func(cfg awssdk.Config) any { return costexplorer.NewFromConfig(cfg) },
	"costoptimizationhub":              func(cfg awssdk.Config) any { return costoptimizationhub.NewFromConfig(cfg) },
	"customerprofiles":                 func(cfg awssdk.Config) any { return customerprofiles.NewFromConfig(cfg) },
	"databasemigrationservice":         func(cfg awssdk.Config) any { return databasemigrationservice.NewFromConfig(cfg) },
	"databrew":                         func(cfg awssdk.Config) any { return databrew.NewFromConfig(cfg) },
	"dataexchange":                     func(cfg awssdk.Config) any { return dataexchange.NewFromConfig(cfg) },
	"datapipeline":                     func(cfg awssdk.Config) any { return datapipeline.NewFromConfig(cfg) },
	"datasync":                         func(cfg awssdk.Config) any { return datasync.NewFromConfig(cfg) },
	"datazone":                         func(cfg awssdk.Config) any { return datazone.NewFromConfig(cfg) },
	"dax":                              func(cfg awssdk.Config) any { return dax.NewFromConfig(cfg) },
	"deadline":                         func(cfg awssdk.Config) any { return deadline.NewFromConfig(cfg) },
	"detective":                        func(cfg awssdk.Config) any { return detective.NewFromConfig(cfg) },
	"devicefarm":                       func(cfg awssdk.Config) any { return devicefarm.NewFromConfig(cfg) },
	"devopsagent":                      func(cfg awssdk.Config) any { return devopsagent.NewFromConfig(cfg) },
	"devopsguru":                       func(cfg awssdk.Config) any { return devopsguru.NewFromConfig(cfg) },
	"directconnect":                    func(cfg awssdk.Config) any { return directconnect.NewFromConfig(cfg) },
	"directoryservice":                 func(cfg awssdk.Config) any { return directoryservice.NewFromConfig(cfg) },
	"directoryservicedata":             func(cfg awssdk.Config) any { return directoryservicedata.NewFromConfig(cfg) },
	"dlm":                              func(cfg awssdk.Config) any { return dlm.NewFromConfig(cfg) },
	"docdb":                            func(cfg awssdk.Config) any { return docdb.NewFromConfig(cfg) },
	"docdbelastic":                     func(cfg awssdk.Config) any { return docdbelastic.NewFromConfig(cfg) },
	"drs":                              func(cfg awssdk.Config) any { return drs.NewFromConfig(cfg) },
	"dsql":                             func(cfg awssdk.Config) any { return dsql.NewFromConfig(cfg) },
	"dynamodb":                         func(cfg awssdk.Config) any { return dynamodb.NewFromConfig(cfg) },
	"dynamodbstreams":                  func(cfg awssdk.Config) any { return dynamodbstreams.NewFromConfig(cfg) },
	"ebs":                              func(cfg awssdk.Config) any { return ebs.NewFromConfig(cfg) },
	"ec2":                              func(cfg awssdk.Config) any { return ec2.NewFromConfig(cfg) },
	"ec2instanceconnect":               func(cfg awssdk.Config) any { return ec2instanceconnect.NewFromConfig(cfg) },
	"ecr":                              func(cfg awssdk.Config) any { return ecr.NewFromConfig(cfg) },
	"ecrpublic":                        func(cfg awssdk.Config) any { return ecrpublic.NewFromConfig(cfg) },
	"ecs":                              func(cfg awssdk.Config) any { return ecs.NewFromConfig(cfg) },
	"efs":                              func(cfg awssdk.Config) any { return efs.NewFromConfig(cfg) },
	"eks":                              func(cfg awssdk.Config) any { return eks.NewFromConfig(cfg) },
	"eksauth":                          func(cfg awssdk.Config) any { return eksauth.NewFromConfig(cfg) },
	"elasticache":                      func(cfg awssdk.Config) any { return elasticache.NewFromConfig(cfg) },
	"elasticbeanstalk":                 func(cfg awssdk.Config) any { return elasticbeanstalk.NewFromConfig(cfg) },
	"elasticloadbalancing":             func(cfg awssdk.Config) any { return elasticloadbalancing.NewFromConfig(cfg) },
	"elasticloadbalancingv2":           func(cfg awssdk.Config) any { return elasticloadbalancingv2.NewFromConfig(cfg) },
	"elasticsearchservice":             func(cfg awssdk.Config) any { return elasticsearchservice.NewFromConfig(cfg) },
	"elementalinference":               func(cfg awssdk.Config) any { return elementalinference.NewFromConfig(cfg) },
	"emr":                              func(cfg awssdk.Config) any { return emr.NewFromConfig(cfg) },
	"emrcontainers":                    func(cfg awssdk.Config) any { return emrcontainers.NewFromConfig(cfg) },
	"emrserverless":                    func(cfg awssdk.Config) any { return emrserverless.NewFromConfig(cfg) },
	"entityresolution":                 func(cfg awssdk.Config) any { return entityresolution.NewFromConfig(cfg) },
	"eventbridge":                      func(cfg awssdk.Config) any { return eventbridge.NewFromConfig(cfg) },
	"evs":                              func(cfg awssdk.Config) any { return evs.NewFromConfig(cfg) },
	"finspace":                         func(cfg awssdk.Config) any { return finspace.NewFromConfig(cfg) },
	"finspacedata":                     func(cfg awssdk.Config) any { return finspacedata.NewFromConfig(cfg) },
	"firehose":                         func(cfg awssdk.Config) any { return firehose.NewFromConfig(cfg) },
	"fis":                              func(cfg awssdk.Config) any { return fis.NewFromConfig(cfg) },
	"fms":                              func(cfg awssdk.Config) any { return fms.NewFromConfig(cfg) },
	"forecast":                         func(cfg awssdk.Config) any { return forecast.NewFromConfig(cfg) },
	"forecastquery":                    func(cfg awssdk.Config) any { return forecastquery.NewFromConfig(cfg) },
	"frauddetector":                    func(cfg awssdk.Config) any { return frauddetector.NewFromConfig(cfg) },
	"freetier":                         func(cfg awssdk.Config) any { return freetier.NewFromConfig(cfg) },
	"fsx":                              func(cfg awssdk.Config) any { return fsx.NewFromConfig(cfg) },
	"gamelift":                         func(cfg awssdk.Config) any { return gamelift.NewFromConfig(cfg) },
	"gameliftstreams":                  func(cfg awssdk.Config) any { return gameliftstreams.NewFromConfig(cfg) },
	"geomaps":                          func(cfg awssdk.Config) any { return geomaps.NewFromConfig(cfg) },
	"geoplaces":                        func(cfg awssdk.Config) any { return geoplaces.NewFromConfig(cfg) },
	"georoutes":                        func(cfg awssdk.Config) any { return georoutes.NewFromConfig(cfg) },
	"glacier":                          func(cfg awssdk.Config) any { return glacier.NewFromConfig(cfg) },
	"globalaccelerator":                func(cfg awssdk.Config) any { return globalaccelerator.NewFromConfig(cfg) },
	"glue":                             func(cfg awssdk.Config) any { return glue.NewFromConfig(cfg) },
	"grafana":                          func(cfg awssdk.Config) any { return grafana.NewFromConfig(cfg) },
	"greengrass":                       func(cfg awssdk.Config) any { return greengrass.NewFromConfig(cfg) },
	"greengrassv2":                     func(cfg awssdk.Config) any { return greengrassv2.NewFromConfig(cfg) },
	"groundstation":                    func(cfg awssdk.Config) any { return groundstation.NewFromConfig(cfg) },
	"guardduty":                        func(cfg awssdk.Config) any { return guardduty.NewFromConfig(cfg) },
	"health":                           func(cfg awssdk.Config) any { return health.NewFromConfig(cfg) },
	"healthlake":                       func(cfg awssdk.Config) any { return healthlake.NewFromConfig(cfg) },
	"iam":                              func(cfg awssdk.Config) any { return iam.NewFromConfig(cfg) },
	"identitystore":                    func(cfg awssdk.Config) any { return identitystore.NewFromConfig(cfg) },
	"imagebuilder":                     func(cfg awssdk.Config) any { return imagebuilder.NewFromConfig(cfg) },
	"inspector":                        func(cfg awssdk.Config) any { return inspector.NewFromConfig(cfg) },
	"inspector2":                       func(cfg awssdk.Config) any { return inspector2.NewFromConfig(cfg) },
	"inspectorscan":                    func(cfg awssdk.Config) any { return inspectorscan.NewFromConfig(cfg) },
	"interconnect":                     func(cfg awssdk.Config) any { return interconnect.NewFromConfig(cfg) },
	"internetmonitor":                  func(cfg awssdk.Config) any { return internetmonitor.NewFromConfig(cfg) },
	"invoicing":                        func(cfg awssdk.Config) any { return invoicing.NewFromConfig(cfg) },
	"iot":                              func(cfg awssdk.Config) any { return iot.NewFromConfig(cfg) },
	"iotdataplane":                     func(cfg awssdk.Config) any { return iotdataplane.NewFromConfig(cfg) },
	"iotdeviceadvisor":                 func(cfg awssdk.Config) any { return iotdeviceadvisor.NewFromConfig(cfg) },
	"iotfleetwise":                     func(cfg awssdk.Config) any { return iotfleetwise.NewFromConfig(cfg) },
	"iotjobsdataplane":                 func(cfg awssdk.Config) any { return iotjobsdataplane.NewFromConfig(cfg) },
	"iotmanagedintegrations":           func(cfg awssdk.Config) any { return iotmanagedintegrations.NewFromConfig(cfg) },
	"iotsecuretunneling":               func(cfg awssdk.Config) any { return iotsecuretunneling.NewFromConfig(cfg) },
	"iotsitewise":                      func(cfg awssdk.Config) any { return iotsitewise.NewFromConfig(cfg) },
	"iotthingsgraph":                   func(cfg awssdk.Config) any { return iotthingsgraph.NewFromConfig(cfg) },
	"iottwinmaker":                     func(cfg awssdk.Config) any { return iottwinmaker.NewFromConfig(cfg) },
	"iotwireless":                      func(cfg awssdk.Config) any { return iotwireless.NewFromConfig(cfg) },
	"ivs":                              func(cfg awssdk.Config) any { return ivs.NewFromConfig(cfg) },
	"ivschat":                          func(cfg awssdk.Config) any { return ivschat.NewFromConfig(cfg) },
	"ivsrealtime":                      func(cfg awssdk.Config) any { return ivsrealtime.NewFromConfig(cfg) },
	"kafka":                            func(cfg awssdk.Config) any { return kafka.NewFromConfig(cfg) },
	"kafkaconnect":                     func(cfg awssdk.Config) any { return kafkaconnect.NewFromConfig(cfg) },
	"kendra":                           func(cfg awssdk.Config) any { return kendra.NewFromConfig(cfg) },
	"kendraranking":                    func(cfg awssdk.Config) any { return kendraranking.NewFromConfig(cfg) },
	"keyspaces":                        func(cfg awssdk.Config) any { return keyspaces.NewFromConfig(cfg) },
	"keyspacesstreams":                 func(cfg awssdk.Config) any { return keyspacesstreams.NewFromConfig(cfg) },
	"kinesis":                          func(cfg awssdk.Config) any { return kinesis.NewFromConfig(cfg) },
	"kinesisanalytics":                 func(cfg awssdk.Config) any { return kinesisanalytics.NewFromConfig(cfg) },
	"kinesisanalyticsv2":               func(cfg awssdk.Config) any { return kinesisanalyticsv2.NewFromConfig(cfg) },
	"kinesisvideo":                     func(cfg awssdk.Config) any { return kinesisvideo.NewFromConfig(cfg) },
	"kinesisvideoarchivedmedia":        func(cfg awssdk.Config) any { return kinesisvideoarchivedmedia.NewFromConfig(cfg) },
	"kinesisvideomedia":                func(cfg awssdk.Config) any { return kinesisvideomedia.NewFromConfig(cfg) },
	"kinesisvideosignaling":            func(cfg awssdk.Config) any { return kinesisvideosignaling.NewFromConfig(cfg) },
	"kinesisvideowebrtcstorage":        func(cfg awssdk.Config) any { return kinesisvideowebrtcstorage.NewFromConfig(cfg) },
	"kms":                              func(cfg awssdk.Config) any { return kms.NewFromConfig(cfg) },
	"lakeformation":                    func(cfg awssdk.Config) any { return lakeformation.NewFromConfig(cfg) },
	"lambda":                           func(cfg awssdk.Config) any { return lambda.NewFromConfig(cfg) },
	"lambdacore":                       func(cfg awssdk.Config) any { return lambdacore.NewFromConfig(cfg) },
	"lambdamicrovms":                   func(cfg awssdk.Config) any { return lambdamicrovms.NewFromConfig(cfg) },
	"launchwizard":                     func(cfg awssdk.Config) any { return launchwizard.NewFromConfig(cfg) },
	"lexmodelbuildingservice":          func(cfg awssdk.Config) any { return lexmodelbuildingservice.NewFromConfig(cfg) },
	"lexmodelsv2":                      func(cfg awssdk.Config) any { return lexmodelsv2.NewFromConfig(cfg) },
	"lexruntimeservice":                func(cfg awssdk.Config) any { return lexruntimeservice.NewFromConfig(cfg) },
	"lexruntimev2":                     func(cfg awssdk.Config) any { return lexruntimev2.NewFromConfig(cfg) },
	"licensemanager":                   func(cfg awssdk.Config) any { return licensemanager.NewFromConfig(cfg) },
	"licensemanagerlinuxsubscriptions": func(cfg awssdk.Config) any { return licensemanagerlinuxsubscriptions.NewFromConfig(cfg) },
	"licensemanagerusersubscriptions":  func(cfg awssdk.Config) any { return licensemanagerusersubscriptions.NewFromConfig(cfg) },
	"lightsail":                        func(cfg awssdk.Config) any { return lightsail.NewFromConfig(cfg) },
	"location":                         func(cfg awssdk.Config) any { return location.NewFromConfig(cfg) },
	"lookoutequipment":                 func(cfg awssdk.Config) any { return lookoutequipment.NewFromConfig(cfg) },
	"m2":                               func(cfg awssdk.Config) any { return m2.NewFromConfig(cfg) },
	"machinelearning":                  func(cfg awssdk.Config) any { return machinelearning.NewFromConfig(cfg) },
	"macie2":                           func(cfg awssdk.Config) any { return macie2.NewFromConfig(cfg) },
	"mailmanager":                      func(cfg awssdk.Config) any { return mailmanager.NewFromConfig(cfg) },
	"managedblockchain":                func(cfg awssdk.Config) any { return managedblockchain.NewFromConfig(cfg) },
	"managedblockchainquery":           func(cfg awssdk.Config) any { return managedblockchainquery.NewFromConfig(cfg) },
	"marketplaceagreement":             func(cfg awssdk.Config) any { return marketplaceagreement.NewFromConfig(cfg) },
	"marketplacecatalog":               func(cfg awssdk.Config) any { return marketplacecatalog.NewFromConfig(cfg) },
	"marketplacecommerceanalytics":     func(cfg awssdk.Config) any { return marketplacecommerceanalytics.NewFromConfig(cfg) },
	"marketplacedeployment":            func(cfg awssdk.Config) any { return marketplacedeployment.NewFromConfig(cfg) },
	"marketplacediscovery":             func(cfg awssdk.Config) any { return marketplacediscovery.NewFromConfig(cfg) },
	"marketplaceentitlementservice":    func(cfg awssdk.Config) any { return marketplaceentitlementservice.NewFromConfig(cfg) },
	"marketplacemetering":              func(cfg awssdk.Config) any { return marketplacemetering.NewFromConfig(cfg) },
	"marketplacereporting":             func(cfg awssdk.Config) any { return marketplacereporting.NewFromConfig(cfg) },
	"mediaconnect":                     func(cfg awssdk.Config) any { return mediaconnect.NewFromConfig(cfg) },
	"mediaconvert":                     func(cfg awssdk.Config) any { return mediaconvert.NewFromConfig(cfg) },
	"medialive":                        func(cfg awssdk.Config) any { return medialive.NewFromConfig(cfg) },
	"mediapackage":                     func(cfg awssdk.Config) any { return mediapackage.NewFromConfig(cfg) },
	"mediapackagev2":                   func(cfg awssdk.Config) any { return mediapackagev2.NewFromConfig(cfg) },
	"mediapackagevod":                  func(cfg awssdk.Config) any { return mediapackagevod.NewFromConfig(cfg) },
	"mediastore":                       func(cfg awssdk.Config) any { return mediastore.NewFromConfig(cfg) },
	"mediastoredata":                   func(cfg awssdk.Config) any { return mediastoredata.NewFromConfig(cfg) },
	"mediatailor":                      func(cfg awssdk.Config) any { return mediatailor.NewFromConfig(cfg) },
	"medicalimaging":                   func(cfg awssdk.Config) any { return medicalimaging.NewFromConfig(cfg) },
	"memorydb":                         func(cfg awssdk.Config) any { return memorydb.NewFromConfig(cfg) },
	"mgn":                              func(cfg awssdk.Config) any { return mgn.NewFromConfig(cfg) },
	"migrationhub":                     func(cfg awssdk.Config) any { return migrationhub.NewFromConfig(cfg) },
	"migrationhubconfig":               func(cfg awssdk.Config) any { return migrationhubconfig.NewFromConfig(cfg) },
	"migrationhuborchestrator":         func(cfg awssdk.Config) any { return migrationhuborchestrator.NewFromConfig(cfg) },
	"migrationhubrefactorspaces":       func(cfg awssdk.Config) any { return migrationhubrefactorspaces.NewFromConfig(cfg) },
	"migrationhubstrategy":             func(cfg awssdk.Config) any { return migrationhubstrategy.NewFromConfig(cfg) },
	"mpa":                              func(cfg awssdk.Config) any { return mpa.NewFromConfig(cfg) },
	"mq":                               func(cfg awssdk.Config) any { return mq.NewFromConfig(cfg) },
	"mturk":                            func(cfg awssdk.Config) any { return mturk.NewFromConfig(cfg) },
	"mwaa":                             func(cfg awssdk.Config) any { return mwaa.NewFromConfig(cfg) },
	"mwaaserverless":                   func(cfg awssdk.Config) any { return mwaaserverless.NewFromConfig(cfg) },
	"neptune":                          func(cfg awssdk.Config) any { return neptune.NewFromConfig(cfg) },
	"neptunedata":                      func(cfg awssdk.Config) any { return neptunedata.NewFromConfig(cfg) },
	"neptunegraph":                     func(cfg awssdk.Config) any { return neptunegraph.NewFromConfig(cfg) },
	"networkfirewall":                  func(cfg awssdk.Config) any { return networkfirewall.NewFromConfig(cfg) },
	"networkflowmonitor":               func(cfg awssdk.Config) any { return networkflowmonitor.NewFromConfig(cfg) },
	"networkmanager":                   func(cfg awssdk.Config) any { return networkmanager.NewFromConfig(cfg) },
	"networkmonitor":                   func(cfg awssdk.Config) any { return networkmonitor.NewFromConfig(cfg) },
	"notifications":                    func(cfg awssdk.Config) any { return notifications.NewFromConfig(cfg) },
	"notificationscontacts":            func(cfg awssdk.Config) any { return notificationscontacts.NewFromConfig(cfg) },
	"novaact":                          func(cfg awssdk.Config) any { return novaact.NewFromConfig(cfg) },
	"oam":                              func(cfg awssdk.Config) any { return oam.NewFromConfig(cfg) },
	"observabilityadmin":               func(cfg awssdk.Config) any { return observabilityadmin.NewFromConfig(cfg) },
	"odb":                              func(cfg awssdk.Config) any { return odb.NewFromConfig(cfg) },
	"omics":                            func(cfg awssdk.Config) any { return omics.NewFromConfig(cfg) },
	"opensearch":                       func(cfg awssdk.Config) any { return opensearch.NewFromConfig(cfg) },
	"opensearchserverless":             func(cfg awssdk.Config) any { return opensearchserverless.NewFromConfig(cfg) },
	"organizations":                    func(cfg awssdk.Config) any { return organizations.NewFromConfig(cfg) },
	"osis":                             func(cfg awssdk.Config) any { return osis.NewFromConfig(cfg) },
	"outposts":                         func(cfg awssdk.Config) any { return outposts.NewFromConfig(cfg) },
	"partnercentralaccount":            func(cfg awssdk.Config) any { return partnercentralaccount.NewFromConfig(cfg) },
	"partnercentralbenefits":           func(cfg awssdk.Config) any { return partnercentralbenefits.NewFromConfig(cfg) },
	"partnercentralchannel":            func(cfg awssdk.Config) any { return partnercentralchannel.NewFromConfig(cfg) },
	"partnercentralselling":            func(cfg awssdk.Config) any { return partnercentralselling.NewFromConfig(cfg) },
	"paymentcryptography":              func(cfg awssdk.Config) any { return paymentcryptography.NewFromConfig(cfg) },
	"paymentcryptographydata":          func(cfg awssdk.Config) any { return paymentcryptographydata.NewFromConfig(cfg) },
	"pcaconnectorad":                   func(cfg awssdk.Config) any { return pcaconnectorad.NewFromConfig(cfg) },
	"pcaconnectorscep":                 func(cfg awssdk.Config) any { return pcaconnectorscep.NewFromConfig(cfg) },
	"pcs":                              func(cfg awssdk.Config) any { return pcs.NewFromConfig(cfg) },
	"personalize":                      func(cfg awssdk.Config) any { return personalize.NewFromConfig(cfg) },
	"personalizeevents":                func(cfg awssdk.Config) any { return personalizeevents.NewFromConfig(cfg) },
	"personalizeruntime":               func(cfg awssdk.Config) any { return personalizeruntime.NewFromConfig(cfg) },
	"pi":                               func(cfg awssdk.Config) any { return pi.NewFromConfig(cfg) },
	"pinpoint":                         func(cfg awssdk.Config) any { return pinpoint.NewFromConfig(cfg) },
	"pinpointemail":                    func(cfg awssdk.Config) any { return pinpointemail.NewFromConfig(cfg) },
	"pinpointsmsvoice":                 func(cfg awssdk.Config) any { return pinpointsmsvoice.NewFromConfig(cfg) },
	"pinpointsmsvoicev2":               func(cfg awssdk.Config) any { return pinpointsmsvoicev2.NewFromConfig(cfg) },
	"pipes":                            func(cfg awssdk.Config) any { return pipes.NewFromConfig(cfg) },
	"polly":                            func(cfg awssdk.Config) any { return polly.NewFromConfig(cfg) },
	"pricing":                          func(cfg awssdk.Config) any { return pricing.NewFromConfig(cfg) },
	"proton":                           func(cfg awssdk.Config) any { return proton.NewFromConfig(cfg) },
	"qapps":                            func(cfg awssdk.Config) any { return qapps.NewFromConfig(cfg) },
	"qbusiness":                        func(cfg awssdk.Config) any { return qbusiness.NewFromConfig(cfg) },
	"qconnect":                         func(cfg awssdk.Config) any { return qconnect.NewFromConfig(cfg) },
	"quicksight":                       func(cfg awssdk.Config) any { return quicksight.NewFromConfig(cfg) },
	"ram":                              func(cfg awssdk.Config) any { return ram.NewFromConfig(cfg) },
	"rbin":                             func(cfg awssdk.Config) any { return rbin.NewFromConfig(cfg) },
	"rds":                              func(cfg awssdk.Config) any { return rds.NewFromConfig(cfg) },
	"rdsdata":                          func(cfg awssdk.Config) any { return rdsdata.NewFromConfig(cfg) },
	"redshift":                         func(cfg awssdk.Config) any { return redshift.NewFromConfig(cfg) },
	"redshiftdata":                     func(cfg awssdk.Config) any { return redshiftdata.NewFromConfig(cfg) },
	"redshiftserverless":               func(cfg awssdk.Config) any { return redshiftserverless.NewFromConfig(cfg) },
	"rekognition":                      func(cfg awssdk.Config) any { return rekognition.NewFromConfig(cfg) },
	"repostspace":                      func(cfg awssdk.Config) any { return repostspace.NewFromConfig(cfg) },
	"resiliencehub":                    func(cfg awssdk.Config) any { return resiliencehub.NewFromConfig(cfg) },
	"resiliencehubv2":                  func(cfg awssdk.Config) any { return resiliencehubv2.NewFromConfig(cfg) },
	"resourceexplorer2":                func(cfg awssdk.Config) any { return resourceexplorer2.NewFromConfig(cfg) },
	"resourcegroups":                   func(cfg awssdk.Config) any { return resourcegroups.NewFromConfig(cfg) },
	"resourcegroupstaggingapi":         func(cfg awssdk.Config) any { return resourcegroupstaggingapi.NewFromConfig(cfg) },
	"rolesanywhere":                    func(cfg awssdk.Config) any { return rolesanywhere.NewFromConfig(cfg) },
	"route53":                          func(cfg awssdk.Config) any { return route53.NewFromConfig(cfg) },
	"route53domains":                   func(cfg awssdk.Config) any { return route53domains.NewFromConfig(cfg) },
	"route53globalresolver":            func(cfg awssdk.Config) any { return route53globalresolver.NewFromConfig(cfg) },
	"route53profiles":                  func(cfg awssdk.Config) any { return route53profiles.NewFromConfig(cfg) },
	"route53recoverycluster":           func(cfg awssdk.Config) any { return route53recoverycluster.NewFromConfig(cfg) },
	"route53recoverycontrolconfig":     func(cfg awssdk.Config) any { return route53recoverycontrolconfig.NewFromConfig(cfg) },
	"route53recoveryreadiness":         func(cfg awssdk.Config) any { return route53recoveryreadiness.NewFromConfig(cfg) },
	"route53resolver":                  func(cfg awssdk.Config) any { return route53resolver.NewFromConfig(cfg) },
	"rtbfabric":                        func(cfg awssdk.Config) any { return rtbfabric.NewFromConfig(cfg) },
	"rum":                              func(cfg awssdk.Config) any { return rum.NewFromConfig(cfg) },
	"s3":                               func(cfg awssdk.Config) any { return s3.NewFromConfig(cfg) },
	"s3control":                        func(cfg awssdk.Config) any { return s3control.NewFromConfig(cfg) },
	"s3files":                          func(cfg awssdk.Config) any { return s3files.NewFromConfig(cfg) },
	"s3outposts":                       func(cfg awssdk.Config) any { return s3outposts.NewFromConfig(cfg) },
	"s3tables":                         func(cfg awssdk.Config) any { return s3tables.NewFromConfig(cfg) },
	"s3vectors":                        func(cfg awssdk.Config) any { return s3vectors.NewFromConfig(cfg) },
	"sagemaker":                        func(cfg awssdk.Config) any { return sagemaker.NewFromConfig(cfg) },
	"sagemakera2iruntime":              func(cfg awssdk.Config) any { return sagemakera2iruntime.NewFromConfig(cfg) },
	"sagemakeredge":                    func(cfg awssdk.Config) any { return sagemakeredge.NewFromConfig(cfg) },
	"sagemakerfeaturestoreruntime":     func(cfg awssdk.Config) any { return sagemakerfeaturestoreruntime.NewFromConfig(cfg) },
	"sagemakergeospatial":              func(cfg awssdk.Config) any { return sagemakergeospatial.NewFromConfig(cfg) },
	"sagemakerjobruntime":              func(cfg awssdk.Config) any { return sagemakerjobruntime.NewFromConfig(cfg) },
	"sagemakermetrics":                 func(cfg awssdk.Config) any { return sagemakermetrics.NewFromConfig(cfg) },
	"sagemakerruntime":                 func(cfg awssdk.Config) any { return sagemakerruntime.NewFromConfig(cfg) },
	"sagemakerruntimehttp2":            func(cfg awssdk.Config) any { return sagemakerruntimehttp2.NewFromConfig(cfg) },
	"savingsplans":                     func(cfg awssdk.Config) any { return savingsplans.NewFromConfig(cfg) },
	"scheduler":                        func(cfg awssdk.Config) any { return scheduler.NewFromConfig(cfg) },
	"schemas":                          func(cfg awssdk.Config) any { return schemas.NewFromConfig(cfg) },
	"secretsmanager":                   func(cfg awssdk.Config) any { return secretsmanager.NewFromConfig(cfg) },
	"securityagent":                    func(cfg awssdk.Config) any { return securityagent.NewFromConfig(cfg) },
	"securityhub":                      func(cfg awssdk.Config) any { return securityhub.NewFromConfig(cfg) },
	"securityir":                       func(cfg awssdk.Config) any { return securityir.NewFromConfig(cfg) },
	"securitylake":                     func(cfg awssdk.Config) any { return securitylake.NewFromConfig(cfg) },
	"serverlessapplicationrepository":  func(cfg awssdk.Config) any { return serverlessapplicationrepository.NewFromConfig(cfg) },
	"servicecatalog":                   func(cfg awssdk.Config) any { return servicecatalog.NewFromConfig(cfg) },
	"servicecatalogappregistry":        func(cfg awssdk.Config) any { return servicecatalogappregistry.NewFromConfig(cfg) },
	"servicediscovery":                 func(cfg awssdk.Config) any { return servicediscovery.NewFromConfig(cfg) },
	"servicequotas":                    func(cfg awssdk.Config) any { return servicequotas.NewFromConfig(cfg) },
	"ses":                              func(cfg awssdk.Config) any { return ses.NewFromConfig(cfg) },
	"sesv2":                            func(cfg awssdk.Config) any { return sesv2.NewFromConfig(cfg) },
	"sfn":                              func(cfg awssdk.Config) any { return sfn.NewFromConfig(cfg) },
	"shield":                           func(cfg awssdk.Config) any { return shield.NewFromConfig(cfg) },
	"signer":                           func(cfg awssdk.Config) any { return signer.NewFromConfig(cfg) },
	"signerdata":                       func(cfg awssdk.Config) any { return signerdata.NewFromConfig(cfg) },
	"signin":                           func(cfg awssdk.Config) any { return signin.NewFromConfig(cfg) },
	"simpledbv2":                       func(cfg awssdk.Config) any { return simpledbv2.NewFromConfig(cfg) },
	"snowball":                         func(cfg awssdk.Config) any { return snowball.NewFromConfig(cfg) },
	"snowdevicemanagement":             func(cfg awssdk.Config) any { return snowdevicemanagement.NewFromConfig(cfg) },
	"sns":                              func(cfg awssdk.Config) any { return sns.NewFromConfig(cfg) },
	"socialmessaging":                  func(cfg awssdk.Config) any { return socialmessaging.NewFromConfig(cfg) },
	"sqs":                              func(cfg awssdk.Config) any { return sqs.NewFromConfig(cfg) },
	"ssm":                              func(cfg awssdk.Config) any { return ssm.NewFromConfig(cfg) },
	"ssmcontacts":                      func(cfg awssdk.Config) any { return ssmcontacts.NewFromConfig(cfg) },
	"ssmguiconnect":                    func(cfg awssdk.Config) any { return ssmguiconnect.NewFromConfig(cfg) },
	"ssmincidents":                     func(cfg awssdk.Config) any { return ssmincidents.NewFromConfig(cfg) },
	"ssmquicksetup":                    func(cfg awssdk.Config) any { return ssmquicksetup.NewFromConfig(cfg) },
	"ssmsap":                           func(cfg awssdk.Config) any { return ssmsap.NewFromConfig(cfg) },
	"sso":                              func(cfg awssdk.Config) any { return sso.NewFromConfig(cfg) },
	"ssoadmin":                         func(cfg awssdk.Config) any { return ssoadmin.NewFromConfig(cfg) },
	"ssooidc":                          func(cfg awssdk.Config) any { return ssooidc.NewFromConfig(cfg) },
	"storagegateway":                   func(cfg awssdk.Config) any { return storagegateway.NewFromConfig(cfg) },
	"sts":                              func(cfg awssdk.Config) any { return sts.NewFromConfig(cfg) },
	"supplychain":                      func(cfg awssdk.Config) any { return supplychain.NewFromConfig(cfg) },
	"support":                          func(cfg awssdk.Config) any { return support.NewFromConfig(cfg) },
	"supportapp":                       func(cfg awssdk.Config) any { return supportapp.NewFromConfig(cfg) },
	"supportauthz":                     func(cfg awssdk.Config) any { return supportauthz.NewFromConfig(cfg) },
	"sustainability":                   func(cfg awssdk.Config) any { return sustainability.NewFromConfig(cfg) },
	"swf":                              func(cfg awssdk.Config) any { return swf.NewFromConfig(cfg) },
	"synthetics":                       func(cfg awssdk.Config) any { return synthetics.NewFromConfig(cfg) },
	"taxsettings":                      func(cfg awssdk.Config) any { return taxsettings.NewFromConfig(cfg) },
	"textract":                         func(cfg awssdk.Config) any { return textract.NewFromConfig(cfg) },
	"timestreaminfluxdb":               func(cfg awssdk.Config) any { return timestreaminfluxdb.NewFromConfig(cfg) },
	"timestreamquery":                  func(cfg awssdk.Config) any { return timestreamquery.NewFromConfig(cfg) },
	"timestreamwrite":                  func(cfg awssdk.Config) any { return timestreamwrite.NewFromConfig(cfg) },
	"tnb":                              func(cfg awssdk.Config) any { return tnb.NewFromConfig(cfg) },
	"transcribe":                       func(cfg awssdk.Config) any { return transcribe.NewFromConfig(cfg) },
	"transcribestreaming":              func(cfg awssdk.Config) any { return transcribestreaming.NewFromConfig(cfg) },
	"transfer":                         func(cfg awssdk.Config) any { return transfer.NewFromConfig(cfg) },
	"translate":                        func(cfg awssdk.Config) any { return translate.NewFromConfig(cfg) },
	"trustedadvisor":                   func(cfg awssdk.Config) any { return trustedadvisor.NewFromConfig(cfg) },
	"uxc":                              func(cfg awssdk.Config) any { return uxc.NewFromConfig(cfg) },
	"verifiedpermissions":              func(cfg awssdk.Config) any { return verifiedpermissions.NewFromConfig(cfg) },
	"voiceid":                          func(cfg awssdk.Config) any { return voiceid.NewFromConfig(cfg) },
	"vpclattice":                       func(cfg awssdk.Config) any { return vpclattice.NewFromConfig(cfg) },
	"waf":                              func(cfg awssdk.Config) any { return waf.NewFromConfig(cfg) },
	"wafregional":                      func(cfg awssdk.Config) any { return wafregional.NewFromConfig(cfg) },
	"wafv2":                            func(cfg awssdk.Config) any { return wafv2.NewFromConfig(cfg) },
	"wellarchitected":                  func(cfg awssdk.Config) any { return wellarchitected.NewFromConfig(cfg) },
	"wickr":                            func(cfg awssdk.Config) any { return wickr.NewFromConfig(cfg) },
	"wisdom":                           func(cfg awssdk.Config) any { return wisdom.NewFromConfig(cfg) },
	"workdocs":                         func(cfg awssdk.Config) any { return workdocs.NewFromConfig(cfg) },
	"workmail":                         func(cfg awssdk.Config) any { return workmail.NewFromConfig(cfg) },
	"workmailmessageflow":              func(cfg awssdk.Config) any { return workmailmessageflow.NewFromConfig(cfg) },
	"workspaces":                       func(cfg awssdk.Config) any { return workspaces.NewFromConfig(cfg) },
	"workspacesinstances":              func(cfg awssdk.Config) any { return workspacesinstances.NewFromConfig(cfg) },
	"workspacesthinclient":             func(cfg awssdk.Config) any { return workspacesthinclient.NewFromConfig(cfg) },
	"workspacesweb":                    func(cfg awssdk.Config) any { return workspacesweb.NewFromConfig(cfg) },
	"xray":                             func(cfg awssdk.Config) any { return xray.NewFromConfig(cfg) },
}
