// Code generated by internal/gen/services from services.json; DO NOT EDIT.
// SPDX-License-Identifier: MIT

package registry

import (
	awssdk "github.com/aws/aws-sdk-go-v2/aws"
	acm "github.com/aws/aws-sdk-go-v2/service/acm"
	apigateway "github.com/aws/aws-sdk-go-v2/service/apigateway"
	apigatewayv2 "github.com/aws/aws-sdk-go-v2/service/apigatewayv2"
	appsync "github.com/aws/aws-sdk-go-v2/service/appsync"
	athena "github.com/aws/aws-sdk-go-v2/service/athena"
	backup "github.com/aws/aws-sdk-go-v2/service/backup"
	batch "github.com/aws/aws-sdk-go-v2/service/batch"
	bedrockruntime "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
	cloudformation "github.com/aws/aws-sdk-go-v2/service/cloudformation"
	cloudfront "github.com/aws/aws-sdk-go-v2/service/cloudfront"
	cloudtrail "github.com/aws/aws-sdk-go-v2/service/cloudtrail"
	cloudwatch "github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	codebuild "github.com/aws/aws-sdk-go-v2/service/codebuild"
	codedeploy "github.com/aws/aws-sdk-go-v2/service/codedeploy"
	codepipeline "github.com/aws/aws-sdk-go-v2/service/codepipeline"
	cognitoidentityprovider "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	comprehend "github.com/aws/aws-sdk-go-v2/service/comprehend"
	docdb "github.com/aws/aws-sdk-go-v2/service/docdb"
	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	ecr "github.com/aws/aws-sdk-go-v2/service/ecr"
	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	efs "github.com/aws/aws-sdk-go-v2/service/efs"
	eks "github.com/aws/aws-sdk-go-v2/service/eks"
	elasticache "github.com/aws/aws-sdk-go-v2/service/elasticache"
	elasticbeanstalk "github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk"
	emr "github.com/aws/aws-sdk-go-v2/service/emr"
	eventbridge "github.com/aws/aws-sdk-go-v2/service/eventbridge"
	firehose "github.com/aws/aws-sdk-go-v2/service/firehose"
	glue "github.com/aws/aws-sdk-go-v2/service/glue"
	iam "github.com/aws/aws-sdk-go-v2/service/iam"
	kinesis "github.com/aws/aws-sdk-go-v2/service/kinesis"
	kms "github.com/aws/aws-sdk-go-v2/service/kms"
	lambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	neptune "github.com/aws/aws-sdk-go-v2/service/neptune"
	opensearch "github.com/aws/aws-sdk-go-v2/service/opensearch"
	organizations "github.com/aws/aws-sdk-go-v2/service/organizations"
	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	redshift "github.com/aws/aws-sdk-go-v2/service/redshift"
	rekognition "github.com/aws/aws-sdk-go-v2/service/rekognition"
	route53 "github.com/aws/aws-sdk-go-v2/service/route53"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	sagemaker "github.com/aws/aws-sdk-go-v2/service/sagemaker"
	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	sfn "github.com/aws/aws-sdk-go-v2/service/sfn"
	sns "github.com/aws/aws-sdk-go-v2/service/sns"
	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	textract "github.com/aws/aws-sdk-go-v2/service/textract"
	transcribe "github.com/aws/aws-sdk-go-v2/service/transcribe"
	wafv2 "github.com/aws/aws-sdk-go-v2/service/wafv2"
)

// Factories maps every configured AWS service name to a constructor for its
// SDK client. Regenerate with: go run ./internal/gen/services (or
// "make generate") after editing services.json.
var Factories = map[string]ClientFactory{
	"acm":                     func(cfg awssdk.Config) any { return acm.NewFromConfig(cfg) },
	"apigateway":              func(cfg awssdk.Config) any { return apigateway.NewFromConfig(cfg) },
	"apigatewayv2":            func(cfg awssdk.Config) any { return apigatewayv2.NewFromConfig(cfg) },
	"appsync":                 func(cfg awssdk.Config) any { return appsync.NewFromConfig(cfg) },
	"athena":                  func(cfg awssdk.Config) any { return athena.NewFromConfig(cfg) },
	"backup":                  func(cfg awssdk.Config) any { return backup.NewFromConfig(cfg) },
	"batch":                   func(cfg awssdk.Config) any { return batch.NewFromConfig(cfg) },
	"bedrockruntime":          func(cfg awssdk.Config) any { return bedrockruntime.NewFromConfig(cfg) },
	"cloudformation":          func(cfg awssdk.Config) any { return cloudformation.NewFromConfig(cfg) },
	"cloudfront":              func(cfg awssdk.Config) any { return cloudfront.NewFromConfig(cfg) },
	"cloudtrail":              func(cfg awssdk.Config) any { return cloudtrail.NewFromConfig(cfg) },
	"cloudwatch":              func(cfg awssdk.Config) any { return cloudwatch.NewFromConfig(cfg) },
	"codebuild":               func(cfg awssdk.Config) any { return codebuild.NewFromConfig(cfg) },
	"codedeploy":              func(cfg awssdk.Config) any { return codedeploy.NewFromConfig(cfg) },
	"codepipeline":            func(cfg awssdk.Config) any { return codepipeline.NewFromConfig(cfg) },
	"cognitoidentityprovider": func(cfg awssdk.Config) any { return cognitoidentityprovider.NewFromConfig(cfg) },
	"comprehend":              func(cfg awssdk.Config) any { return comprehend.NewFromConfig(cfg) },
	"docdb":                   func(cfg awssdk.Config) any { return docdb.NewFromConfig(cfg) },
	"dynamodb":                func(cfg awssdk.Config) any { return dynamodb.NewFromConfig(cfg) },
	"ec2":                     func(cfg awssdk.Config) any { return ec2.NewFromConfig(cfg) },
	"ecr":                     func(cfg awssdk.Config) any { return ecr.NewFromConfig(cfg) },
	"ecs":                     func(cfg awssdk.Config) any { return ecs.NewFromConfig(cfg) },
	"efs":                     func(cfg awssdk.Config) any { return efs.NewFromConfig(cfg) },
	"eks":                     func(cfg awssdk.Config) any { return eks.NewFromConfig(cfg) },
	"elasticache":             func(cfg awssdk.Config) any { return elasticache.NewFromConfig(cfg) },
	"elasticbeanstalk":        func(cfg awssdk.Config) any { return elasticbeanstalk.NewFromConfig(cfg) },
	"emr":                     func(cfg awssdk.Config) any { return emr.NewFromConfig(cfg) },
	"eventbridge":             func(cfg awssdk.Config) any { return eventbridge.NewFromConfig(cfg) },
	"firehose":                func(cfg awssdk.Config) any { return firehose.NewFromConfig(cfg) },
	"glue":                    func(cfg awssdk.Config) any { return glue.NewFromConfig(cfg) },
	"iam":                     func(cfg awssdk.Config) any { return iam.NewFromConfig(cfg) },
	"kinesis":                 func(cfg awssdk.Config) any { return kinesis.NewFromConfig(cfg) },
	"kms":                     func(cfg awssdk.Config) any { return kms.NewFromConfig(cfg) },
	"lambda":                  func(cfg awssdk.Config) any { return lambda.NewFromConfig(cfg) },
	"neptune":                 func(cfg awssdk.Config) any { return neptune.NewFromConfig(cfg) },
	"opensearch":              func(cfg awssdk.Config) any { return opensearch.NewFromConfig(cfg) },
	"organizations":           func(cfg awssdk.Config) any { return organizations.NewFromConfig(cfg) },
	"rds":                     func(cfg awssdk.Config) any { return rds.NewFromConfig(cfg) },
	"redshift":                func(cfg awssdk.Config) any { return redshift.NewFromConfig(cfg) },
	"rekognition":             func(cfg awssdk.Config) any { return rekognition.NewFromConfig(cfg) },
	"route53":                 func(cfg awssdk.Config) any { return route53.NewFromConfig(cfg) },
	"s3":                      func(cfg awssdk.Config) any { return s3.NewFromConfig(cfg) },
	"sagemaker":               func(cfg awssdk.Config) any { return sagemaker.NewFromConfig(cfg) },
	"secretsmanager":          func(cfg awssdk.Config) any { return secretsmanager.NewFromConfig(cfg) },
	"sfn":                     func(cfg awssdk.Config) any { return sfn.NewFromConfig(cfg) },
	"sns":                     func(cfg awssdk.Config) any { return sns.NewFromConfig(cfg) },
	"sqs":                     func(cfg awssdk.Config) any { return sqs.NewFromConfig(cfg) },
	"ssm":                     func(cfg awssdk.Config) any { return ssm.NewFromConfig(cfg) },
	"sts":                     func(cfg awssdk.Config) any { return sts.NewFromConfig(cfg) },
	"textract":                func(cfg awssdk.Config) any { return textract.NewFromConfig(cfg) },
	"transcribe":              func(cfg awssdk.Config) any { return transcribe.NewFromConfig(cfg) },
	"wafv2":                   func(cfg awssdk.Config) any { return wafv2.NewFromConfig(cfg) },
}
